{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}
{% set rname = "r-aws.signature" %}
{% set name = "aws.signature" %}
{% set version = "0.2.9" %}
{% set sha256 = "5f11ff63203733d7bae0d8cb8ca2ed0a2ee03f0cdfa5407466062314baf98f13" %}

package:
  name: {{ rname|lower }}
  version: {{ version }}

source:
  fn: {{ name }}_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/{{ name }}_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/{{ name }}/{{ name }}_{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-digest
    - r-base64enc

  run:
    - r-base
    - r-digest
    - r-base64enc

test:
  commands:
    - $R -e "library('aws.signature')"  # [not win]
    - "\"%R%\" -e \"library('aws.signature')\""  # [win]

about:
  home: https://cran.r-project.org/web/packages/aws.signature/index.html
  license: GPL (>= 2)
  summary: 'Generates request signatures for Amazon Web Services (AWS) APIs'
  license_family: GPL2
  doc_url: https://cran.r-project.org/web/packages/aws.signature/aws.signature.pdf
  dev_url: https://github.com/cloudyr/aws.signature

extra:
  recipe-maintainers:
    - benvandyke

# The original CRAN metadata for this package was:

# Package: aws.signature
# Type: Package
# Title: Amazon Web Services Request Signatures
# Version: 0.2.9
# Date: 2017-04-28
# Authors@R: c(person("Thomas J.", "Leeper", role = c("aut", "cre"),
#                    email = "thosjleeper@gmail.com"))
# Description: Generates request signatures for Amazon Web Services (AWS) APIs.
# License: GPL (>= 2)
# Imports:
#    digest,
#    base64enc,
#    aws.ec2metadata
# Suggests:
#    testthat
# URL: https://github.com/cloudyr/aws.signature
# BugReports: https://github.com/cloudyr/aws.signature/issues
# RoxygenNote: 6.0.1
